### ISSUE TITLE
Zero coverage

### ISSUE THREAD

**Issue by almogon** [yuriburger/sonar-ts-demo#2]
Hi, 
I try follow your tutorial and do every step, but when I run sonar, the execution is success but with zero coverage .

08:58:17.580 INFO: Scanner configuration file: /home/alvaro/.sonar/native-sonar-scanner/sonar-scanner-3.2.0.1227-linux/conf/sonar-scanner.properties
08:58:17.585 INFO: Project root configuration file: /home/alvaro/Documents/Projects/sonar-ts-demo/sonar-project.properties
08:58:17.604 INFO: SonarQube Scanner 3.2.0.1227
08:58:17.605 INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
08:58:17.605 INFO: Linux 4.15.0-34-generic amd64
08:58:17.739 DEBUG: keyStore is : 
08:58:17.739 DEBUG: keyStore type is : jks
08:58:17.739 DEBUG: keyStore provider is : 
08:58:17.739 DEBUG: init keystore
08:58:17.740 DEBUG: init keymanager of type SunX509
08:58:17.814 DEBUG: Create: /home/alvaro/.sonar/cache
08:58:17.815 INFO: User cache: /home/alvaro/.sonar/cache
08:58:17.815 DEBUG: Create: /home/alvaro/.sonar/cache/_tmp
08:58:17.818 DEBUG: Extract sonar-scanner-api-batch in temp...
08:58:17.823 DEBUG: Get bootstrap index...
08:58:17.823 DEBUG: Download: http://localhost:9000/batch/index
08:58:17.875 DEBUG: Get bootstrap completed
08:58:17.883 DEBUG: Create isolated classloader...
08:58:17.889 DEBUG: Start temp cleaning...
08:58:17.894 DEBUG: Temp cleaning done
08:58:17.894 DEBUG: Execution getVersion
08:58:17.896 INFO: SonarQube server 6.4.0
08:58:17.897 INFO: Default locale: "en_US", source code encoding: "UTF-8"
08:58:17.897 DEBUG: Work directory: /home/alvaro/Documents/Projects/sonar-ts-demo/.scannerwork
08:58:17.898 DEBUG: Execution execute
08:58:18.081 DEBUG: Publish global mode
08:58:18.205 INFO: Load global settings
08:58:18.249 DEBUG: GET 200 http://localhost:9000/api/settings/values.protobuf | time=36ms
08:58:18.276 INFO: Load global settings (done) | time=72ms
08:58:18.301 INFO: User cache: /home/alvaro/.sonar/cache
08:58:18.575 INFO: Load plugins index
08:58:18.577 DEBUG: GET 200 http://localhost:9000/deploy/plugins/index.txt | time=2ms
08:58:18.579 INFO: Load plugins index (done) | time=4ms
08:58:18.579 DEBUG: Load plugins
08:58:18.627 DEBUG: Load plugins (done) | time=48ms
08:58:18.656 DEBUG: API compatibility mode is enabled on plugin Git [scmgit] (built with API lower than 5.2)
08:58:18.660 DEBUG: API compatibility mode is enabled on plugin SVN [scmsvn] (built with API lower than 5.2)
08:58:18.785 DEBUG: Plugins:
08:58:18.786 DEBUG:   * Python 1.7.0.1195 (python)
08:58:18.786 DEBUG:   * C# 5.10.1.1411 (csharp)
08:58:18.786 DEBUG:   * SonarJava 4.9.0.9858 (java)
08:58:18.786 DEBUG:   * Flex 2.3 (flex)
08:58:18.786 DEBUG:   * SonarXML 1.4.2.885 (xml)
08:58:18.787 DEBUG:   * Git 1.2 (scmgit)
08:58:18.787 DEBUG:   * SonarPHP 2.10.0.2087 (php)
08:58:18.787 DEBUG:   * SVN 1.4.0.522 (scmsvn)
08:58:18.787 DEBUG:   * SonarJS 3.0.0.4962 (javascript)
08:58:19.276 INFO: Process project properties
08:58:19.281 DEBUG: Process project properties (done) | time=4ms
08:58:19.411 INFO: Load project repositories
08:58:19.435 DEBUG: GET 200 http://localhost:9000/batch/project.protobuf?key=Demo%3Asonar-ts-demo | time=17ms
08:58:19.539 INFO: Load project repositories (done) | time=128ms
08:58:19.637 DEBUG: Available languages:
08:58:19.637 DEBUG:   * Python => "py"
08:58:19.637 DEBUG:   * C# => "cs"
08:58:19.638 DEBUG:   * Java => "java"
08:58:19.638 DEBUG:   * Flex => "flex"
08:58:19.638 DEBUG:   * XML => "xml"
08:58:19.638 DEBUG:   * PHP => "php"
08:58:19.638 DEBUG:   * JavaScript => "js"
08:58:19.642 INFO: Load quality profiles
08:58:19.653 DEBUG: GET 200 http://localhost:9000/api/qualityprofiles/search.protobuf?projectKey=Demo%3Asonar-ts-demo | time=10ms
08:58:19.674 INFO: Load quality profiles (done) | time=32ms
08:58:19.678 INFO: Load active rules
08:58:19.722 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AWXsz_rqciNqbTfFzvJe&p=1&ps=500 | time=44ms
08:58:19.904 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AWXsz_xyciNqbTfFzvL_&p=1&ps=500 | time=95ms
08:58:19.983 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AWXsz_2ociNqbTfFzvQP&p=1&ps=500 | time=52ms
08:58:20.010 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AWXsz_3ZciNqbTfFzvRM&p=1&ps=500 | time=23ms
08:58:20.050 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AWXsz_5fciNqbTfFzvTb&p=1&ps=500 | time=38ms
08:58:20.077 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AWXsz_4KciNqbTfFzvRx&p=1&ps=500 | time=23ms
08:58:20.121 DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives,createdAt&activation=true&qprofile=AWXsz_3lciNqbTfFzvRO&p=1&ps=500 | time=40ms
08:58:20.141 INFO: Load active rules (done) | time=463ms
08:58:20.144 INFO: Load metrics repository
08:58:20.167 DEBUG: GET 200 http://localhost:9000/api/metrics/search?f=name,description,direction,qualitative,custom&ps=500&p=1 | time=22ms
08:58:20.276 INFO: Load metrics repository (done) | time=132ms
08:58:20.299 DEBUG: SCM Step is disabled by configuration
08:58:20.300 INFO: Publish mode
08:58:20.300 INFO: Project key: Demo:sonar-ts-demo
08:58:20.301 DEBUG: Start recursive analysis of project modules
08:58:20.303 INFO: -------------  Scan Sonar TS Demo
08:58:20.526 INFO: Load server rules
08:58:20.549 DEBUG: GET 200 http://localhost:9000/api/rules/list.protobuf | time=22ms
08:58:20.562 INFO: Load server rules (done) | time=36ms
08:58:20.698 DEBUG: Declared extensions of language Python were converted to sonar.lang.patterns.py : **/*.py
08:58:20.699 DEBUG: Declared extensions of language C# were converted to sonar.lang.patterns.cs : **/*.cs
08:58:20.699 DEBUG: Declared extensions of language Java were converted to sonar.lang.patterns.java : **/*.java,**/*.jav
08:58:20.699 DEBUG: Declared extensions of language Flex were converted to sonar.lang.patterns.flex : **/*.as
08:58:20.699 DEBUG: Declared extensions of language XML were converted to sonar.lang.patterns.xml : **/*.xml,**/*.xsd,**/*.xsl
08:58:20.699 DEBUG: Declared extensions of language PHP were converted to sonar.lang.patterns.php : **/*.php,**/*.php3,**/*.php4,**/*.php5,**/*.phtml,**/*.inc
08:58:20.700 DEBUG: Declared extensions of language JavaScript were converted to sonar.lang.patterns.js : **/*.js,**/*.ts
08:58:20.770 DEBUG: Initializers : GenericCoverageSensor
08:58:20.771 INFO: Initializer GenericCoverageSensor
08:58:20.771 INFO: Initializer GenericCoverageSensor (done) | time=1ms
08:58:20.771 INFO: Base dir: /home/alvaro/Documents/Projects/sonar-ts-demo
08:58:20.771 INFO: Working dir: /home/alvaro/Documents/Projects/sonar-ts-demo/.scannerwork
08:58:20.773 INFO: Source paths: src
08:58:20.773 INFO: Test paths: src
08:58:20.773 INFO: Source encoding: UTF-8, default locale: en_US
08:58:20.775 INFO: Index files
08:58:20.776 INFO: Excluded sources: 
08:58:20.777 INFO:   **/node_modules/**
08:58:20.777 INFO:   **/*.spec.ts
08:58:20.777 INFO:   **/*.spec.ts
08:58:20.777 INFO: Included tests: 
08:58:20.777 INFO:   **/*.spec.ts
08:58:20.803 DEBUG: 'src/hello.service.interface.ts' indexed with language 'js'
08:58:20.806 DEBUG: 'src/hello.component.spec.ts' indexed as test with language 'js'
08:58:20.810 DEBUG: 'src/hello.component.ts' indexed with language 'js'
08:58:20.810 INFO: 3 files indexed
08:58:20.811 INFO: 3 files ignored because of inclusion/exclusion patterns
08:58:20.812 INFO: Quality profile for js: Sonar way Recommended
08:58:21.589 DEBUG: 'Generic Coverage Report' skipped because one of the required properties is missing
08:58:21.589 DEBUG: 'Generic Test Executions Report' skipped because one of the required properties is missing
08:58:21.590 DEBUG: 'Python Squid Sensor' skipped because there is no related file in current project
08:58:21.590 DEBUG: 'C#' skipped because there is no related file in current project
08:58:21.590 DEBUG: 'C# Unit Tests Coverage Report Import' skipped because there is no related file in current project
08:58:21.590 DEBUG: 'C# Integration Tests Coverage Report Import' skipped because there is no related file in current project
08:58:21.591 DEBUG: 'C# Unit Test Results Import' skipped because there is no related file in current project
08:58:21.591 DEBUG: 'SurefireSensor' skipped because there is no related file in current project
08:58:21.591 DEBUG: 'JaCoCoSensor' skipped because there is no related file in current project
08:58:21.591 DEBUG: 'JavaSquidSensor' skipped because there is no related file in current project
08:58:21.592 DEBUG: 'Flex' skipped because there is no related file in current project
08:58:21.592 DEBUG: 'Flex Cobertura' skipped because there is no related file in current project
08:58:21.592 DEBUG: 'XML Sensor' skipped because there is no related file in current project
08:58:21.592 DEBUG: 'PHP sensor' skipped because there is no related file in current project
08:58:21.595 DEBUG: 'Generic Coverage Report' skipped because one of the required properties is missing
08:58:21.595 DEBUG: 'Generic Test Executions Report' skipped because one of the required properties is missing
08:58:21.595 DEBUG: 'Python Squid Sensor' skipped because there is no related file in current project
08:58:21.595 DEBUG: 'C#' skipped because there is no related file in current project
08:58:21.596 DEBUG: 'C# Unit Tests Coverage Report Import' skipped because there is no related file in current project
08:58:21.596 DEBUG: 'C# Integration Tests Coverage Report Import' skipped because there is no related file in current project
08:58:21.596 DEBUG: 'C# Unit Test Results Import' skipped because there is no related file in current project
08:58:21.596 DEBUG: 'SurefireSensor' skipped because there is no related file in current project
08:58:21.596 DEBUG: 'JaCoCoSensor' skipped because there is no related file in current project
08:58:21.596 DEBUG: 'JavaSquidSensor' skipped because there is no related file in current project
08:58:21.597 DEBUG: 'Flex' skipped because there is no related file in current project
08:58:21.597 DEBUG: 'Flex Cobertura' skipped because there is no related file in current project
08:58:21.597 DEBUG: 'XML Sensor' skipped because there is no related file in current project
08:58:21.597 DEBUG: 'PHP sensor' skipped because there is no related file in current project
08:58:21.603 DEBUG: Sensors : SonarJavaXmlFileSensor -> Analyzer for "php.ini" files -> JavaScript Squid Sensor -> Zero Coverage Sensor -> CPD Block Indexer
08:58:21.603 INFO: Sensor SonarJavaXmlFileSensor [java]
08:58:21.604 INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=1ms
08:58:21.604 INFO: Sensor Analyzer for "php.ini" files [php]
08:58:21.610 INFO: Sensor Analyzer for "php.ini" files [php] (done) | time=6ms
08:58:21.611 INFO: Sensor JavaScript Squid Sensor [javascript]
08:58:21.617 INFO: 2 source files to be analyzed
08:58:21.644 DEBUG: 'src/hello.component.ts' generated metadata  with charset 'UTF-8'
08:58:21.658 ERROR: Unable to parse file: /home/alvaro/Documents/Projects/sonar-ts-demo/src/hello.component.ts
08:58:21.658 ERROR: Parse error at line 5 column 25:

```
import { IHelloService } from "./hello.service.interface";
export class HelloComponent {
    constructor(private helloService: IHelloService) {}
                        ^
     public sayHello(): string {
         return this.helloService.sayHello();
     }
```
08:58:21.663 DEBUG: 'src/hello.service.interface.ts' generated metadata  with charset 'UTF-8'
08:58:21.665 ERROR: Unable to parse file: /home/alvaro/Documents/Projects/sonar-ts-demo/src/hello.service.interface.ts
08:58:21.665 ERROR: Parse error at line 1 column 18:

```
export interface IHelloService {
                 ^
   sayHello(): string;
}
```

08:58:21.666 INFO: 2/2 source files have been analyzed
08:58:21.671 INFO: Unit Test Coverage Sensor is started
08:58:21.673 INFO: Integration Test Coverage Sensor is started
08:58:21.674 INFO: Overall Coverage Sensor is started
08:58:21.674 INFO: Sensor JavaScript Squid Sensor [javascript] (done) | time=63ms
08:58:21.675 INFO: Sensor Zero Coverage Sensor
08:58:21.692 INFO: Sensor Zero Coverage Sensor (done) | time=18ms
08:58:21.693 INFO: Sensor CPD Block Indexer
08:58:21.693 DEBUG: org.sonar.scanner.cpd.deprecated.DefaultCpdBlockIndexer is used for js
08:58:21.694 DEBUG: No CpdMapping for language js
08:58:21.694 INFO: Sensor CPD Block Indexer (done) | time=2ms
08:58:21.694 INFO: SCM Publisher is disabled
08:58:21.695 INFO: Calculating CPD for 0 files
08:58:21.697 INFO: CPD calculation finished
08:58:21.863 DEBUG: 'src/hello.component.spec.ts' generated metadata as test  with charset 'UTF-8'
08:58:21.883 INFO: Analysis report generated in 185ms, dir size=30 KB
08:58:21.896 INFO: Analysis reports compressed in 13ms, zip size=9 KB
08:58:21.897 INFO: Analysis report generated in /home/alvaro/Documents/Projects/sonar-ts-demo/.scannerwork/batch-report
08:58:21.897 DEBUG: Upload report
08:58:21.963 DEBUG: POST 200 http://localhost:9000/api/ce/submit?projectKey=Demo:sonar-ts-demo&projectName=Sonar%20TS%20Demo | time=65ms
08:58:21.965 INFO: Analysis report uploaded in 68ms
08:58:21.966 INFO: ANALYSIS SUCCESSFUL, you can browse http://localhost:9000/dashboard/index/Demo:sonar-ts-demo
08:58:21.966 INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
08:58:21.966 INFO: More about the report processing at http://localhost:9000/api/ce/task?id=AWYe-J6C0t70iFDmM_W6
08:58:21.966 DEBUG: Report metadata written to /home/alvaro/Documents/Projects/sonar-ts-demo/.scannerwork/report-task.txt
08:58:21.968 DEBUG: Post-jobs : 
08:58:21.971 INFO: Task total time: 3.149 s
08:58:22.098 INFO: ------------------------------------------------------------------------
08:58:22.098 INFO: EXECUTION SUCCESS
08:58:22.098 INFO: ------------------------------------------------------------------------
08:58:22.098 INFO: Total time: 4.536s
08:58:22.173 INFO: Final Memory: 9M/214M
08:58:22.175 INFO: ------------------------------------------------------------------------

What is it wrong or what I dont have ?
thanks

**Comment by yuriburger** [comment]
Hi, 
I don't see Sonar picking up your coverage file (lcov.info). Can you make sure one is generated by karma ("npm run test")? It should be located in your projects .\coverage directory. 

Hope this helps, 

Yuri

**Comment by almogon** [comment]
Yes I have it. 
I copy the file code : 
`TN:
SF:/home/xxxx/Documents/Projects/sonar-ts-demo/src/hello.component.ts
FN:3,(anonymous_3)
FN:5,HelloComponent
FN:7,(anonymous_5)
FNF:3
FNH:3
FNDA:1,(anonymous_3)
FNDA:1,HelloComponent
FNDA:1,(anonymous_5)
DA:3,1
DA:5,1
DA:7,1
DA:8,1
DA:10,1
LF:5
LH:5
BRF:0
BRH:0
end_of_record
TN:
SF:/home/xxxx/Documents/Projects/sonar-ts-demo/src/hello.service.interface.ts
FNF:0
FNH:0
LF:0
LH:0
BRF:0
BRH:0
end_of_record`

Maybe is some configuration i need in my sonar server and i miss it ??
Thanks for your help

**Comment by almogon** [comment]
I discover the problem is with sonarserver , has not good configurate sonarTS script. I close the issue. Thank you
